#!/usr/bin/env bash
# Build the deployable tree: what actually goes on chain, and the /preview twin.
#
# Two things this fixes that deploying straight from the repository does not.
#
# 1. `gnokey maketx addpkg` packs the directory with MPUserAll, which INCLUDES
#    *_test.gno (gno.land/pkg/keyscli/addpkg.go). Deploying from the working
#    tree would put the whole test suite on chain and pay a storage deposit on
#    it forever, at 100 ugnot/byte, for bytes nobody on chain can run. The
#    monorepo's own tools/gnopublish avoids this by packing MPUserProd instead;
#    this does the same thing with a directory. Measured on this repo:
#    the realm is 39,134 bytes with tests and 22,366 without, so 43% of a
#    permanent deposit would buy nothing a reader of the chain can run.
#
# 2. There is no testnet to stage on, so the staging environment is a second
#    realm on the same chain: gno.land/r/<ns>/<name>/preview, flagged
#    private = true so the path stays redeployable while the design moves. The
#    production path is deployed once and is then permanent.
#
# Only gnomod.toml differs between the two. If anything else ever has to, the
# design is wrong: a realm that behaves differently in staging is not the thing
# you tested.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"
rm -rf _stage
mkdir -p _stage
# _stage is its own gno workspace, so gnopm resolves the staged copies and not
# the ones in the working tree. Without it, publishing from here would plan the
# tree it was trying to avoid.
printf '# generated by scripts/stage.sh; _stage/ is rebuilt from scratch.\n' > _stage/gnowork.toml

copy() { # <srcdir> <destdir> — source, README and gnomod.toml. No tests.
  mkdir -p "$2"
  find "$1" -maxdepth 1 -name '*.gno' -not -name '*_test.gno' -exec cp {} "$2/" \;
  [ -f "$1/README.md" ] && cp "$1/README.md" "$2/"
  cp "$1/gnomod.toml" "$2/gnomod.toml"
}

bytes() { find "$1" -type f -exec cat {} + | wc -c | tr -d ' '; }

exec 3>&1 1>&2   # everything below is commentary; keep stdout clean for a pipe
printf '%-44s %10s %10s\n' package "on chain" "in repo"
for mod in $(find p r -name gnomod.toml | sort); do
  src="$(dirname "$mod")"
  path="$(sed -n 's/^module = "\(.*\)"/\1/p' "$mod")"
  copy "$src" "_stage/${path#gno.land/}"
  printf '%-44s %10s %10s\n' "$path" "$(bytes "_stage/${path#gno.land/}")" "$(bytes "$src")"

  # Every realm gets a preview twin. A pure package does not: it is versioned
  # and immutable, so a second copy would just spend another path.
  case "$src" in
    r/*)
      out="_stage/${path#gno.land/}/preview"
      copy "$src" "$out"
      printf 'module = "%s/preview"\ngno = "0.9"\nprivate = true\n' "$path" > "$out/gnomod.toml"
      printf '%-44s %10s %10s\n' "$path/preview" "$(bytes "$out")" "-"
      ;;
  esac
done

# gnopm needs a lock to resolve a workspace. _stage/ is regenerated from scratch
# every time, so this one is derived, never committed and never the authority:
# the repository's own gnomod.lock is.
#
# Optional, because only publishing needs it. CI stages on every run to check
# that the twin still builds, and a hard dependency on a second tool there made
# the whole gate red for a reason that had nothing to do with the change.
if command -v gnopm >/dev/null 2>&1; then
  gnopm -C _stage sync >/dev/null
else
  echo "note: gnopm is not installed, so _stage has no lock. Only publishing needs one." >&2
fi

echo
echo "_stage/ is what gets published. Publish with: make publish-print"
exec 1>&3 3>&-
